# 车票的版本，整数，用于和车票nbt中的版本比较，如果不同，则车票自动更新
# =========================== 每次新增车站需要改动 ===========================
express-ticket-version: 1
# ==========================================================================

railway-routes:
